### ISSUE TITLE
Wanted to contact you to ask a question regarding issue that you solved in other repo

### ISSUE THREAD

**Issue by quawoh** [yulidai/chat#1]
https://github.com/cosmos/cosmos-sdk/issues/2973

Hi there, I saw that you solved the issue here, which I was having a similar issue with before using your solution. 

I still don't understand though why that solved the issue/ why we need to do that with Go. Sorry for my ignorance. I am new with Go. If you could help explain or point me toward where I can learn more, that would be great. 

Specifically, why 
"
it's my fault, should reload bash_profile before each export runs
echo "export GOPATH=$HOME/go" >> ~/.bash_profile
echo "export GOBIN=$GOPATH/bin" >> ~/.bash_profile
echo "export PATH=$PATH:$GOBIN" >> ~/.bash_profile
" 
Is necessary
Thanks for your patience and hope to hear from you

**Comment by yulidai** [comment]
Just for setup go environment, you can see more info [here](https://medium.com/@RidhamTarpara/install-go-1-11-on-ubuntu-18-04-16-04-lts-8c098c503c5f)(Step 2) to learn more about it

**Comment by quawoh** [comment]
Got it, I understand now. Thank you for responding.
